DOI-USGS/delaware-basin-story

jenkins/Jenkinsfile.build

First . . .
Finally . . .
Change to name of temp dist directory
-----------

fix to temp dist directory path

---

Dockerfile

First . . .
Finally . . .
Another attempt to fix the temp dist directory path
-----------

actually fix to temp dist directory path

---

jenkins/Jenkinsfile.build
package-lock.json
package.json
src/main.js
src/views/salinity/subViews/SalinityRoad.vue

First . . .
Finally . . .
New Deploy Targets Test
-----------
This adjust to auto deploy to water-visualizations-test-website
also tests a video plugin
Note - if test works we still need to remove the call to the 'qa' bucket which no longer exists
Description
-----------

New deploy target and video test

---

jenkins/Jenkinsfile.build

First . . .
Finally . . .
Title
-----------
Description
-----------

fixed typo

---

jenkins/Jenkinsfile.build

First . . .
Finally . . .
Title
-----------
Description
-----------

revert target

---

.env.qa_tier
build.sh
jenkins/Jenkinsfile.build
package.json

First . . .
Finally . . .
Remove References to 'qa'
-----------
The new system of buckets on AWS no longer has a 'qa' internal tier, so I am removing that from the build process

removed references to qa

---

jenkins/Jenkinsfile.build

First . . .
Finally . . .
Try URL without suffix
-----------

shorten url

---

jenkins/Jenkinsfile.build

First . . .
Finally . . .
Added recursive to the remove
-----------

thinking we need a recusive rm

---

public/index.html

First . . .
Finally . . .
Add Google Tag Manager Connection
-----------
This connects the application to the Google Tag Manager container called delaware-basin-story

Drb story 549 add google tag manager

---

public/index.html

First . . .
Finally . . .
Add JSON-LD meta data
-----------
This provides a basic structure, some minor changes will be needed before release

added json-ld application meta data

---

src/views/intro/Intro.vue

First . . .
Finally . . .
Title
-----------
Description
-----------

teak for mobile

---

.env
.env.prod_tier
public/index.html
src/App.vue

First . . .
Finally . . .
Stop Indexing of Beta Tier
-----------
This adds the 'robots' meta tag that tell search engines not to index a web page. The addition of this tag to the application is conditional on the deployment tier, and as such will not require any additional human interaction to remove the tag when the application is deployed to the 'prod' tier.

added the robots tag and minor related improvements

---

public/index.html

First . . .
Finally . . .
Fixing Quote Type
-----------

add right quote type

---

package-lock.json
package.json
src/main.js
src/views/monitoring/Monitoring.vue

First . . .
Finally . . .
Another in progress request
-----------
This demonstrates highlight on scroll

Initial monitoring images

---

package-lock.json
package.json
src/App.vue
src/components/HeaderUSWDSBanner.vue

First . . .
Finally . . .
Update Wording of USWDS 'official gov' banner
-----------
This updated the USWDS package to current and adds the new wording to the banner. 
Adds content:none to the 'after' pseudo element that holds a white chevron as this is not currently loading

Uswds banner update wording

---

src/views/monitoring/Monitoring.vue

First . . .
Finally . . .
Hide the Scroll Bar
-----------
A quick CSS change for previews

hid the scroll bar

---

package-lock.json
package.json
src/App.vue
src/components/WorkInProgressWarning.vue
src/views/monitoring/Monitoring.vue
src/views/salinity/subViews/SalinitySea.vue

First . . .
Finally . . .
FONTS!
-----------
Added imports for Chantal and Noto Sans to the project

Font chantal add

---

src/views/conclusion/Conclusion.vue
src/views/monitoring/Monitoring.vue

First . . .
Finally . . .
Trigger to Start Conclusion Animation
-----------
This change will start the 'conclusion' animation when the user has the full section in view. This uses Vue's conditional element loading.

Scroll trigger to start conclusion animation

---

src/App.vue
src/views/conclusion/Conclusion.vue
src/views/monitoring/Monitoring.vue
src/views/salinity/Salinity.vue
src/views/salinity/subViews/SalinitySea.vue

First . . .
Finally . . .
Add Scroll Trigger for Sea Level Rise
-----------
This adds the basic functionality of the scroll trigger, but is not intended to present the final formatting.

Drb story 578 sea level scroll trigger

---

src/views/conclusion/Conclusion.vue

First . . .
Finally . . .
Title
-----------
Description
-----------

fix browser compatability for keyframe animations

---

src/views/conclusion/Conclusion.vue

First . . .
Finally . . .
Title
-----------
Description
-----------

add conclusion text

---

src/views/conclusion/Conclusion.vue
src/views/monitoring/Monitoring.vue
src/views/salinity/Salinity.vue
src/views/salinity/subViews/SalinityRoad2.vue

First . . .
Finally . . .
Working on Monitoring Section Layout
-----------
Made monitoring layout block, still haven't fixed the positioning of the number icons and text, nor the sticky positioning
-----------

Working on Monitoring Layout

---

src/views/monitoring/Monitoring.vue
src/views/temperature/Temperature.vue

First . . .
Finally . . .
Fixed Creeping Monitoring
-----------
Realized I needed to start the relative positioning one element lower

fixed my mussel trigger error

---

src/views/monitoring/Monitoring.vue
src/views/temperature/Temperature.vue

First . . .
Finally . . .
Improvement for Monitoring
-----------
Fixed the sticky image
add transition for text. this is not the implementation from the mock up, but making the text pop in produced quite a jarring effect so reluctantly I replaced all that code with a text fade which is a significantly improved user experience.

fixed sticky monitoring map and added transitions

---

src/views/temperature/Temperature.vue

First . . .
Finally . . .
gif added
-----------
Description
-----------
Let's try this again

minor changes to text and positioning of fish

---

public/index.html
src/views/intro/Intro.vue
src/views/intro/subViews/IntroTextContents.vue
src/views/salinity/Salinity.vue
src/views/salinity/subViews/SalinityRoad.vue
src/views/salinity/subViews/SalinitySea.vue

First . . .
Finally . . .
Simplify Road Salt Section CSS with Mobile Pattern
-----------
This greatly reduces the CSS for this section, uses the CSS Grid pattern to standardize code and fixes the sticky position issue that was showing in Android Chrome and Firefox.

Salinity grid part 2

---

jenkins/Jenkinsfile.build

First . . .
Finally . . .
Update the Build Email list
-----------

adjust email list

---

public/index.html

First . . .
Finally . . .
Add Start of Social Media Meta Tags
-----------
This adds the rough outline for the meta tags related to social media
Since a number of items are yet to be determined/confirmed I didn't fill those in. One of more pressing ones is what that desired final URL will be labs.waterdata.usgs.gov/visualizations/name 

added start of meta tags for social media

---

src/views/salinity/Salinity.vue
src/views/salinity/subViews/SalinityRoad.vue
src/views/salinity/subViews/SalinitySea.vue

First . . .
Finally . . .
Title
-----------
Working on https://github.com/usgs-makerspace/makerspace-sandbox/issues/595 and https://github.com/usgs-makerspace/makerspace-sandbox/issues/591
Description
-----------
Added a snow effect to the road salt section that is triggered by the road salt text appearing. Appears over map and turns off when off section. The spacing after this section and scaling with different screen sizes needs to be addressed here .

make it snow!

---

package-lock.json
package.json
src/App.vue
src/components/SankeyTransition.vue
src/components/SectionTitle.vue
src/views/intro/Intro.vue
src/views/monitoringConclusion/MonitoringConclusion.vue
src/views/salinity/subViews/SalinitySea.vue
src/views/temperature/Temperature.vue

First . . .
Finally . . .
Title
-----------
Visual Tweaks to intro and body
Description
-----------
tweaked lowlights
tried a parallax layout for the intro map, didn't quite succeed in doing something awesome
made a class called "text-chunk" to add to chunks of text that should be in a white background group that floats over sticky images in mobile.  Added it to most of the right chunks, but there are still some funky sections in salinity and the monitoring section.

Visual tweaks to intro and body

---

src/views/temperature/Temperature.vue

First . . .
Finally . . .
Title
-----------
Description
-----------
Just some very small fixes!

drop unused animations

---

src/views/monitoringConclusion/MonitoringConclusion.vue

First . . .
Finally . . .
Title
-----------
Description
-----------

fixed end tag 

---

src/views/monitoringConclusion/MonitoringConclusion.vue

First . . .
Finally . . .
Title
-----------
Description
-----------

fix svg placement

---

src/views/monitoringConclusion/MonitoringConclusion.vue

First . . .
Finally . . .
Merged 
-----------
Successfully merged Colleen's monitoring svg edits 
editing header labeling in the monitoring conclusion chunks
-----------

fixed monitoring title font size

---

src/components/ImageCarousel.vue

mobile load not working for safari

---

src/components/SankeyTransition.vue
src/views/monitoringConclusion/MonitoringConclusion.vue
src/views/salinity/subViews/SalinitySea.vue

First . . .
Finally . . .
Updated Text from Kendra
-----------
Description
-----------

Kendra text edits

---

src/App.vue
src/views/intro/Intro.vue
src/views/monitoringConclusion/MonitoringConclusion.vue

First . . .
Finally . . .
Title
-----------
Description
-----------

really not that much, tried to fix the monitoring map sizing but failed

---

package-lock.json
package.json
src/App.vue
src/components/ImageCarousel.vue
src/components/PreFooterVisualizationsLinks.vue
src/main.js
src/views/monitoringConclusion/Monitoring.vue
src/views/temperature/Temperature.vue

added v-img compatibility for lightbox
made halos in monitoring section bigger
-----------
Describe the changes made, reference related issues. Note anything that you want the reviewers to know while
Can confirm this application works on:

very minor tweaks

---

package-lock.json
src/views/flow/Flow.vue
src/views/monitoringConclusion/Conclusion.vue
src/views/temperature/Temperature.vue

Description
-----------
Describe the changes made, reference related issues. Note anything that you want the reviewers to know while
Can confirm this application works on:

lets go oop0oo

---

PULL_REQUEST_TEMPLATE.md
public/index.html
src/views/monitoringConclusion/Monitoring.vue

Description
-----------
Responding to Brian's comments about making it just 45 gages. Edited in the text to parallel flow section and changed highlight to just the "new" and "activated" gages for flow
Can confirm this application works on:

edit new and enhanced gages

---

src/App.vue
src/views/temperature/Temperature.vue

Description
-----------
pull down and see what you think. I like it, it makes the whole thing feel shorter
and can confirm this application works on:

shorter scroll distance

---

src/components/PreFooterVisualizationsLinks.vue

Description
-----------
Describe the changes made reference related issues. Note anything that you want the reviewers to know while
reviewing your pull request. 
and can confirm this application works on:

switch links

---

Dockerfile
package-lock.json
public/index.html

Description
-----------
Small PR to:
* fix the gap at the top of the page that would be added with push to prod of current `index.html`
* refresh the npm cache
* revise the node install script in `Dockerfile` to specify node `v20`
and can confirm this application works on:

Minor fixes
